---
run-name: 'YAML files'

on:
  push:
  workflow_call:

jobs:
  code-quality:
    name: 'yamllint ${{ matrix.module }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['github-actions', 'gitlabci']
    steps:
      - uses: actions/checkout@v3
      - uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: ${{ matrix.module }}
          yamllint_strict: true
          yamllint_config_filepath: 'yamllint-config.yaml'
...
